name: advent_of_code_2024
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-53.0.dev

# Add regular dependencies here.
dependencies:
  collection:
  fast_immutable_collections: ^11.0.0
  meta: ^1.16.0
  more: ^4.4.0
  path:
  trotter: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
